// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Fallback to Android or Web options if Windows is not configured
        // This prevents immediate crashes but proper configuration is recommended
        return android; 
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZoT2bil7OS5ZRuI8YyJGIA-Bqhxbg36g',
    appId: '1:815481747113:web:b0dbc9b84e4c88bec69bb8',
    messagingSenderId: '815481747113',
    projectId: 'fashion-store-app-da5',
    authDomain: 'fashion-store-app-da5.firebaseapp.com',
    storageBucket: 'fashion-store-app-da5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqkrvNld_ga4Is1EXaISLkTSDnT2QLSF4',
    appId: '1:815481747113:android:7cec9202b87f1872c69bb8',
    messagingSenderId: '815481747113',
    projectId: 'fashion-store-app-da5',
    storageBucket: 'fashion-store-app-da5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIp78nok6Y8xWuRQKf_NeqVV_aXDdZuc',
    appId: '1:815481747113:ios:41402f9f2114f2a7c69bb8',
    messagingSenderId: '815481747113',
    projectId: 'fashion-store-app-da5',
    storageBucket: 'fashion-store-app-da5.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtIp78nok6Y8xWuRQKf_NeqVV_aXDdZuc',
    appId: '1:815481747113:ios:41402f9f2114f2a7c69bb8',
    messagingSenderId: '815481747113',
    projectId: 'fashion-store-app-da5',
    storageBucket: 'fashion-store-app-da5.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZoT2bil7OS5ZRuI8YyJGIA-Bqhxbg36g',
    appId: '1:815481747113:web:8817a976eb5893dcc69bb8',
    messagingSenderId: '815481747113',
    projectId: 'fashion-store-app-da5',
    authDomain: 'fashion-store-app-da5.firebaseapp.com',
    storageBucket: 'fashion-store-app-da5.firebasestorage.app',
  );

}